---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_terminal: yes

dotfiles_repo: https://github.com/tonyarnold/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles

homebrew_installed_packages:
  - bat
  - carthage
  - cmake
  - fish
  - git
  - gnupg
  - goenv
  - keychain
  - lazygit
  - mas
  - mergepbx
  - neovim
  - ninja
  - nodenv
  - pinentry
  - pinentry-mac
  - pyenv
  - rbenv
  - swiftformat
  - swiftlint
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - acorn
  - android-studio
  - charles
  - dash
  - docker
  - dropbox
  - firefox
  - google-chrome
  - iconjar
  - kaleidoscope
  - keybase
  - macdown
  - moom
  - omnigraffle
  - pacifist
  - paintcode
  - paparazzi
  - paw
  - reggy
  - reveal
  - simple-comic
  - sketch
  - skype
  - superduper
  - tableplus
  - textexpander
  - tower
  - transmission
  - transmit
  - twist
  - vagrant
  - vmware-fusion
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 497799835, name: "Xcode" }
  - { id: 1107421413, name: "1Blocker" }
  - { id: 1333542190, name: "1Password" }
  - { id: 1287445660, name: "Agenda" }
  - { id: 1319778037, name: "iStat Menus" }
  - { id: 409183694, name: "Keynote" }
  - { id: 441258766, name: "Magnet" }
  - { id: 1289197285, name: "MindNode 5" }
  - { id: 419330170, name: "Moom" }
  - { id: 409203825, name: "Numbers" }
  - { id: 409201541, name: "Pages" }
  - { id: 967805235, name: "Paste" }
  - { id: 1289583905, name: "Pixelmator Pro" }
  - { id: 880001334, name: "Reeder 3" }
  - { id: 803453959, name: "Slack" }
  - { id: 413965349, name: "Soulver" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 904280696, name: "Things 3" }
  - { id: 1384080005, name: "Tweetbot 3" }

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
