---
- hosts: all
  connection: local

  vars_prompt:
    - name: mas_email
      prompt: "Mac App Store login email"
      private: no

  vars_files:
    - default.config.yml

  vars:
    - mas_signin_dialog: yes

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: geerlingguy.homebrew
      tags: ['homebrew']
      
  tasks:
    - include_tasks: tasks/ansible-setup.yml

    - include_tasks: tasks/terminal.yml
      when: configure_terminal

    - include_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - include_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
